name: Grafana Docker Workflow

on:
  workflow_dispatch:

env:
  DOCKERHUB_IMAGE: fakebilly/grafana:10.1.2
  GCHR_DOCKERHUB_IMAGE: grafana:10.1.2
  ALI_DOCKERHUB_IMAGE: monet/grafana:10.1.2

jobs:
  build:
    name: Grafana Image Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.0
        with:
          submodules: recursive

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: GCHR Docker Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ secrets.GCHR_DOCKERHUB_REGISTRY }}
          username: ${{ secrets.GCHR_DOCKERHUB_USERNAME }}
          password: ${{ secrets.GCHR_DOCKERHUB_TOKEN }}

      - name: Ali Docker Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ secrets.ALI_DOCKERHUB_REGISTRY }}
          username: ${{ secrets.ALI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.ALI_DOCKERHUB_TOKEN }}

      - name: Build and Push Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          platforms: |
            linux/amd64
          build-args:
          context: grafana-docker-images
          file: grafana-docker-images/Dockerfile
          no-cache: true
          push: true
          tags: ${{ env.DOCKERHUB_IMAGE }}

      - name: Tag and Push and Remove GCHR Docker images
        run: |
          docker tag ${{ env.DOCKERHUB_IMAGE }} ${{ secrets.GCHR_DOCKERHUB_REGISTRY }}/${{ secrets.GCHR_DOCKERHUB_USERNAME }}/${{ env.GCHR_DOCKERHUB_IMAGE }}
          docker push ${{ secrets.GCHR_DOCKERHUB_REGISTRY }}/${{ secrets.GCHR_DOCKERHUB_USERNAME }}/${{ env.GCHR_DOCKERHUB_IMAGE }}
          docker rmi ${{ secrets.GCHR_DOCKERHUB_REGISTRY }}/${{ secrets.GCHR_DOCKERHUB_USERNAME }}/${{ env.GCHR_DOCKERHUB_IMAGE }}

      - name: Tag and Push and Remove Ali Docker images
        run: |
          docker tag ${{ env.DOCKERHUB_IMAGE }} ${{ secrets.ALI_DOCKERHUB_REGISTRY }}/${{ env.ALI_DOCKERHUB_IMAGE }}
          docker push ${{ secrets.ALI_DOCKERHUB_REGISTRY }}/${{ env.ALI_DOCKERHUB_IMAGE }}
          docker rmi ${{ secrets.ALI_DOCKERHUB_REGISTRY }}/${{ env.ALI_DOCKERHUB_IMAGE }}
          docker rmi ${{ env.DOCKERHUB_IMAGE }}
