name: Ubuntu Workshop Docker Workflow

on:
  workflow_dispatch:

env:
  DOCKERHUB_IMAGE: fakebilly/ubuntu:20.04-workshop
  ALI_DOCKERHUB_REGISTRY: registry.cn-beijing.aliyuncs.com
  ALI_DOCKERHUB_IMAGE: monet/ubuntu:20.04-workshop

jobs:
  build:
    name: Workshop Ubuntu Image Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          platforms: |
            linux/amd64
          build-args:
          context: workshop-docker-images
          file: workshop-docker-images/Dockerfile
          no-cache: true
          push: true
          tags: ${{ env.DOCKERHUB_IMAGE }}

      - name: Tag and Push and Remove Docker images
        run: |
          docker tag ${{ env.DOCKERHUB_IMAGE }} ${{ env.ALI_DOCKERHUB_REGISTRY }}/${{ env.ALI_DOCKERHUB_IMAGE }}
          docker login -u ${{ secrets.ALI_DOCKERHUB_USERNAME }} -p ${{ secrets.ALI_DOCKERHUB_TOKEN }} ${{ env.ALI_DOCKERHUB_REGISTRY }}
          docker push ${{ env.ALI_DOCKERHUB_REGISTRY }}/${{ env.ALI_DOCKERHUB_IMAGE }}
          docker logout ${{ env.ALI_DOCKERHUB_REGISTRY }}
          docker rmi ${{ env.ALI_DOCKERHUB_REGISTRY }}/${{ env.ALI_DOCKERHUB_IMAGE }}
          docker rmi ${{ env.DOCKERHUB_IMAGE }}
